### ISSUE TITLE
fail cases

### ISSUE THREAD

**Issue by Sophiexuer** [google/enjarify#15]
Hi,

I used enjarify to covert some commercial apks into jar files. I found it work well on most cases. However, I still find some fail cases, especially when involving some expection sentences. And many fail cases also fails with the use of dex2jar.

So I would like to know what the reason of it is. And what the main advantage of enjarify is. Does it use some unique methods or just consider some special cases?

Thanks for your help! : )

**Comment by Storyyeller** [comment]
If you provide an example apk, I can take a look and see why it is failing.

**Comment by Sophiexuer** [comment]
Sure, I use com.baidu.input(https://play.google.com/store/apps/details?id=com.baidu.input) to make an experiment to compare enjarify and dex2jar.

**Comment by Storyyeller** [comment]
Running on apk 08af3438a6fa0b47aa020e6711322b6c1c993ec00fc09e43131e2e35041ec0eb, I get 2775 classes translated successfully, 0 classes had errors

If you're seeing errors, you'll have to provide more information about how to reproduce them.

**Comment by Sophiexuer** [comment]
I get the same information indeed. However, when I use jd-gui(versionName: 0.3.6) to read the jar files, I found some errors, for example, generateMD5File in com.baidu.android.appswitchsdk.app.AppSwitchActivity. So I wonder if there are errors with enjarify or with jd-gui, or some replacements of jd-gui.

Thanks.

**Comment by Storyyeller** [comment]
Most likely the errors are with jd-gui.
