### ISSUE TITLE
git tag for packaging

### ISSUE THREAD

**Issue by anthraxx** [google/enjarify#16]
Hey,

any chance to get a git tag to make it easier to package this great tool?
That would be amazing! :smile: 

If yes, then it would be gorgeous if you sometimes create a new tag :yum: 

cheers
anthraxx

**Comment by Storyyeller** [comment]
What do I need to do?

**Comment by anthraxx** [comment]
@Storyyeller creating a git tag and pushing it is enough. Github is so cool and creates automatic tarballs from it.

```
git tag 1.0
git push --tags
```

If you want _sophisticated_ features like changelogs on github, you can edit the release on the github page later, or also use the github page to tag such a release (however i find the native git command more convenient/easy).

After pushing the git tags you will see the tarball here: https://github.com/google/enjarify/releases

PS: it would be awesome if you could do that from time-to-time if you feel like :smile: 
I will move your tool into the Arch Linux repositories and update if on new release versions.

**Comment by Storyyeller** [comment]
I wonder if it'd be worth setting it up to create a tag for every commit automatically. Or should I just add a tag when there's a new feature or bugfix?

**Comment by Storyyeller** [comment]
I went ahead and created a tag. I think I'll try semantic versioning.

**Comment by anthraxx** [comment]
@Storyyeller nah every commit ruins the gain of tags :stuck_out_tongue: 
I would great a new tag sometimes when you did some fixes or added new features and feel like a new release is worth. Would be awesome! merci!
