### ISSUE TITLE
missing tests in tarballs, which can be very handy

### ISSUE THREAD

**Issue by anthraxx** [google/enjarify#18]
Hey, me again... hope I'm not annoying :wink: 

I have another topic that would be great if you could consider it: Re-adding the tests. I have noticed your .gitattributes changes that add git-export ignores that will keep the tests out of the release tarball.
The tests seem to use 1.7 MB... I guess you wanted to get rid of that "bloat"?

From the packaging and distribution point of view i find the tests quite usefull as its always nice and handy if our packaging script can run the upstream tests so we can easily detect possible regressions before we ship the final package to the users.

1.7MB doesn't sound too much nowadays, but I understand if you want to keep that out of your tarball, in such case i can change the build process to pull from a git tag... but first wanted to ask for your feedback and consideration to re-add them :smile: 

cheers and thanks for enjarify!

**Comment by Storyyeller** [comment]
My assumption is that anyone who wants to run the tests would download the full repository. Releases are supposed to be for end users, and it doesn't seem useful to include the tests in that case.

**Comment by anthraxx** [comment]
@Storyyeller I fully see your point now but i still tend to disagree from a Linux distribution point of view :smile: As mentioned nearly all distributions want to run tests before packaging a software if those are available and most of the time we try to simply pick the release tarballs.
But as mentioned, as I see your point and also have a workaround (use git tag instead of your tarballs for packaging) I don't care that much... however immense amount of projects are in fact shipping tests-suits beside their sources.

Feel free to make your decision and either re-add them in general or just close this ticket :yum:
