### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kin9-0rz** [google/enjarify#21]
Samples MD5: e57cef0ba29012303bb775eea88c7087

[Download Link](https://yunpan.cn/cx6V6ZILHJv3z)  Code : `59c1`

**Comment by Storyyeller** [comment]
Looks like it has a big endian dex file. I didn't bother supporting big endian files, since I didn't think it was used or supported anywhere.

**Comment by Storyyeller** [comment]
I think this is WAI. 

I see 

```
    if-lez v9, :cond_a
    move-result-object v1
```

Which is not valid code. Are you able to run this on a real device?

**Comment by kin9-0rz** [comment]
So i'm late, I found this sample could not be installed.
