### ISSUE TITLE
cannot translate debug info

### ISSUE THREAD

**Issue by basherone** [google/enjarify#27]
dex2jar 0.0.9.x(0.0.9.9-0.0.9.15)  can translate debug info from Dalvik ,but it's too old.Is enjarify planned to support translate debug info?

**Comment by Storyyeller** [comment]
Not really. It's not clear to me how dalvik debug info maps to java debug info, and I don't have much time to work on Enjarify. If I did work on it, my first priority would be Java 8 support.
