### ISSUE TITLE
No module named enjarify.main

### ISSUE THREAD

**Issue by quanghd** [google/enjarify#3]
It didn't works. Just show log:

Using python3 as Python interperter
./enjarify/enjarify.sh: line 39: realpath: command not found
/usr/local/bin/python3: No module named enjarify.main

**Comment by Storyyeller** [comment]
I think realpath might be distribution dependent. Do you have it? Which distribution and version are you using?

**Comment by quanghd** [comment]
I've just cloned latest version, i read the enjarify.sh script and I think the main problem is the "enjarify.main" was not exist.

**Comment by power7714** [comment]
I found that changing the call from python3 to just python made it work perfectly. At least for me

**Comment by quanghd** [comment]
Oh, sorry, the mistake is I didn't run the script from its main directory. It works now!

**Comment by quanghd** [comment]
realpath is not exist on Centos OS, but we can use "readpath -e" instead, or just simply use this command:

echo '/usr/bin/readlink -e "$@"' > /usr/local/bin/realpath ; chmod +x /usr/local/bin/realpath

**Comment by wansir** [comment]
./enjarify-1.0.2
python3 -O -m enjarify.main
