### ISSUE TITLE
ACC_SUPER is not set in class file headers

### ISSUE THREAD

**Issue by winstonbond** [google/enjarify#30]
ACC_SUPER may not be used by JVMs (as commented in flags.py), but it is used by the Android dexer. The Dalvik opcode used to call superclass methods depends on whether ACC_SUPER is set in the class file. If ACC_SUPER is not set then the wrong opcode will be used.

enjarify doesn't set the flag, so jars created by enjarify can't be put back through the dexer and run successfully. 

dex2jar sets ACC_SUPER in every class that isn't an interface.

**Comment by Storyyeller** [comment]
I'll go ahead and fix this, but it seems like you should file a bug with the dexer as well.

**Comment by winstonbond** [comment]
Thanks for jumping on it so quickly. 

There is a comment in the code for dx that points to the place in the spec that says it should do different things depending on how ACC_SUPER is set. So I guess they have thought about it.

I have a fix that seems to work and would happily contribute it, but I'm a newbie to git and am still battling with branches, forks, pulls etc.
