### ISSUE TITLE
PyPy3 speed

### ISSUE THREAD

**Issue by ghost** [google/enjarify#34]
I got this results running latest enjarify with latest PyPy3 with Python 3.5 support (hashtests.py using range 10 ):
```
pypy3 -m enjarify.hashtests  21,44s user 0,11s system 99% cpu 21,552 total

python3.5 -m enjarify.hashtests  73,71s user 0,37s system 99% cpu 1:14,09 total
```

So there's ~3.4x speed improvement

**Comment by ghost** [comment]
This is program run log:
http://vmprof.com/#/827941b0e9d82c0059882979af6b3502
You can also go to http://vmprof.com/#/9b5c930d803ce6be13a0f11f67758756/traces
to see generated JIT code, but it will be slow to load (because there's A LOT of generated JIT code)

**Comment by Storyyeller** [comment]
I haven't tried Pypy3 since September. I'll try it again when I get home.

**Comment by ghost** [comment]
@Storyyeller but this is nightly version of alpha PyPy3 with Python 3.5 support.
You can't download it on pypy.org

**Comment by ghost** [comment]
@Storyyeller and yeah, porting enjarify to Python 2 will give more speed under PyPy2

**Comment by Storyyeller** [comment]
I forgot to respond before, but yes, Pypy 3.5 seems to have fixed all the speed issues with the previous Pypy 3k branches. Unfortunately, I can't close issues here any more.
