### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by balidani** [google/enjarify#36]
Traceback:

    com/rise/app/wallet/application/RisingApp.class Traceback (most recent call last):
      File "~/Programs/enjarify/enjarify/main.py", line 38, in translate
        class_data = writeclass.toClassFile(cls, opts)
      File "~/Programs/enjarify/enjarify/jvm/writeclass.py", line 116, in toClassFile
        pool, rest_stream = classFileAfterPool(cls, opts=opts)
      File "~/Programs/enjarify/enjarify/jvm/writeclass.py", line 100, in classFileAfterPool
        writeMethods(pool, stream, cls.data.methods, opts=opts)
      File "~/Programs/enjarify/enjarify/jvm/writeclass.py", line 65, in writeMethods
        code_attrs = writebytecode.finishCodeAttrs(pool, code_irs, opts=opts)
      File "~/Programs/enjarify/enjarify/jvm/writebytecode.py", line 75, in finishCodeAttrs
        return {irdata.method: writeCodeAttributeTail(pool, irdata, opts=opts) for irdata in code_irs}
      File "~/Programs/enjarify/enjarify/jvm/writebytecode.py", line 75, in <dictcomp>
        return {irdata.method: writeCodeAttributeTail(pool, irdata, opts=opts) for irdata in code_irs}
      File "~/Programs/enjarify/enjarify/jvm/writebytecode.py", line 80, in writeCodeAttributeTail
        bytecode, excepts = jumps.createBytecode(irdata)
      File "~/Programs/enjarify/enjarify/jvm/optimization/jumps.py", line 84, in createBytecode
        packed_excepts.append(struct.pack('>HHHH', s_off, e_off, h_off, c))
    struct.error: 'H' format requires 0 <= number <= 65535

Looks like `s_off`, `e_off` and `h_off` can be greater than 65k when a DEX file is large enough.

I tried the following fix and it worked:

```python
    try:
        packed_excepts.append(struct.pack('>HHHH', s_off, e_off, h_off, c))
    except struct.error:
        packed_excepts.append(struct.pack('>IIIH', s_off, e_off, h_off, c))
```

**Comment by Storyyeller** [comment]
This is a fundamental incompatibility between dex and classfiles. Classfiles are limited to 65535 bytes of code per method, while dalvik methods can be much longer.

Enjarify performs a number of optimizations on the code in an attempt to reduce the size below 65535 bytes, but if the input is large enough, then that still won't be enough. If you are able to post the dex file that triggered the error, I can take a look and see if there are any optimizations that could be added to handle it.

**Comment by balidani** [comment]
I see, thanks for the fast reply!

I can't post the DEX, but it's 3.3 MB, so I doubt anything can be done.

**Comment by Storyyeller** [comment]
After looking at it again, I realized that there is a bug which prevents the optimizations from actually taking effect. 

You can try [this](https://github.com/Storyyeller/enjarify/commit/4946b41ce4b78aefb08c2c04ddba2e0419e77523), which should fix it.

Keep in mind that even with the optimizations on, it may or may not succeed, depending on what the input code is like.

**Comment by balidani** [comment]
Unfortunately that didn't work, but thank you for the patch! I suspect the app is too large, as it was split into multiple DEX files.

**Comment by Storyyeller** [comment]
The total size of the dex file doesn't matter, only the size of the largest method. 

Usually, when a single method is very large, it is because there is some source of bloat, like giant array initializers or autogenerated code, since people normally don't code super large methods by hand. So if you could figure out what the code of that method looks like, and whether there is a shorter way to encode that code, that would reduce the size of the method, perhaps enough to bring it under 65535 bytes.

**Comment by balidani** [comment]
The large method in the class causing the problem has a huge byte array initializer with 18k elements. Other than that it does not look too big, so this is probably the cause.

**Comment by Storyyeller** [comment]
Initializing an array of that size in Java bytecode would take around 6.5 bytes per entry even after optimizations. So anything about ~10k will hit the limit, no matter what you try. Oh well.

**Comment by balidani** [comment]
Thanks so much for the insight!
