### ISSUE TITLE
Use Python launcher instead of python3

### ISSUE THREAD

**Issue by FranklinYu** [google/enjarify#37]
Currently `enjarify.bat` calls `python3`, but Python installer doesn't install `python3.exe`. According to [PEP 397](https://www.python.org/dev/peps/pep-0397/), the preferred way is to use Python launcher.

**Comment by Storyyeller** [comment]
It sounds like the launcher scripts were a mistake in the first place. What do you recommend? Should I just get rid of the scripts and add a shebang line?

**Comment by FranklinYu** [comment]
Did you mean that you would like to add another Python script to replace `enjarify.bat`? Or to add the shebang to `enjarify/main.py`?

I'm not sure what's the best way to do so. If we keep the batch file, then simply replace `python3` with `py -3` (without changing any existing option) will do the trick. If we instead create a Python script, then I think there are more than one way to do it.

Actually I'm trying packaging enjarify with [Chocolatey](https://chocolatey.org/), a package manager in Windows. That is easier than download from GitHub, since this package is not on PyPI (right?).

**Comment by FranklinYu** [comment]
Closed by Storyyeller/enjarify#10
