### ISSUE TITLE
realpath: command not found on mac

### ISSUE THREAD

**Issue by kassadin** [google/enjarify#5]
```
Using python3 as Python interperter
/usr/local/bin/enjarify: line 39: realpath: command not found
/usr/local/opt/python3/bin/python3.4: Error while finding spec for 'enjarify.main' (<class 'ImportError'>: No module named 'enjarify')
```

I solved it by
http://blog.ivansiu.com/blog/2014/05/01/os-x-get-full-path-of-file-using-realpath/

**Comment by Storyyeller** [comment]
Sorry, I don't have a mac to test on. If the helper scripts don't work, you can still invoke python directly or create your own script.
