### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by followztx** [google/enjarify#9]
in enjarify.sh line 39:
export PYTHONPATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")

mac osx 10.10.4,there is no realpath command,please replace with readlink command。

**Comment by Storyyeller** [comment]
Unfortunately I don't have a Mac to test on.

Does it just require replacing realpath with readlink?

**Comment by followztx** [comment]
Yes,just replace it with readlink. there are two way.
1.replace "realpath" with "readlink" in the enjarify.sh line 39
2.add a realpath link to readlink（recommended)
echo '/usr/bin/readlink "$@"' > /usr/local/bin/realpath
chmod +x /usr/local/bin/realpath
[more](http://superuser.com/questions/771104/usr-bin-realpath-not-found-in-centos-6-5)

you can test it on windows or linux

**Comment by Storyyeller** [comment]
Should be fixed by https://github.com/google/enjarify/commit/3863097798037de495388f8c5da2d7090dabb4d7
